version: '3.3'

networks:
  core:
    external: true

services:
  link-proxy-workers:
    build:
      context: ../../
      dockerfile: Dockerfile.worker
    networks:
      - core
    depends_on:
      - redis
      - mongo
      - minio
    environment:
      S3_ENDPOINT: http://minio:9000
      MONGO_URL: mongodb://mongo:27017
      REDIS_HOST: redis

  link-proxy-web:
    build:
      context: ../../
      dockerfile: Dockerfile.web
    networks:
      - core
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
      REDIS_HOST: redis
    ports:
      - 5000:5000
