version: '3.3'

networks:
  core:
    driver: bridge

volumes:
  mongo-data: {}
  redis-data: {}
  minio-data: {}

services:
  mongo:
    image: mongo:4.0
    volumes:
      - mongo-data:/data/db
    networks:
      - core
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    networks:
      - core
    ports:
      - 8081:8081

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis-data:/data
    networks:
      - core
    ports:
      - 6379:6379

  arena:
    image: odlevakp/arena:2.4.2
    depends_on:
      - redis
    networks:
      - core
    volumes:
      - ./config/arena.json:/opt/arena/src/server/config/index.json
    ports:
      - 4567:4567

  minio:
    image: minio/minio:RELEASE.2018-09-01T00-38-25Z
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - core
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio-s3cr3t
    ports:
      - 9000:9000
